# Generated by Django 6.1.1 on 2026-09-05 15:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablecimientoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_renaes', models.CharField(blank=True, max_length=20)),
                ('nivel', models.CharField(choices=[('I-1', 'I-1'), ('I-2', 'I-2'), ('I-3', 'I-3'), ('I-4', 'I-4')], max_length=3)),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('tiene_conectividad_estable', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['departamento', 'provincia', 'distrito', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carné de Extranjería')], default='DNI', max_length=3)),
                ('numero_documento', models.CharField(max_length=15)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('edad', models.PositiveSmallIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('OTRO', 'Otro')], max_length=4)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='unique_documento_paciente')],
            },
        ),
        migrations.CreateModel(
            name='CasoTriaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_lesion_predicho', models.CharField(choices=[('akiec', 'Queratosis actínica / enfermedad de Bowen'), ('bcc', 'Carcinoma basocelular'), ('bkl', 'Lesión queratósica benigna'), ('df', 'Dermatofibroma'), ('mel', 'Melanoma'), ('nv', 'Nevo melanocítico'), ('vasc', 'Lesión vascular')], max_length=5)),
                ('confianza_modelo', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('probabilidades_top3', models.JSONField(blank=True, help_text='Top-3 predicciones del modelo, ej. [{"tipo": "mel", "confianza": 0.62}, ...].', null=True)),
                ('modelo_version', models.CharField(blank=True, default='skin-lesion-classifier-mobilenet-ham10000-tfjs', max_length=50)),
                ('clasificacion_riesgo', models.CharField(choices=[('BAJO', 'Bajo riesgo'), ('MEDIO', 'Riesgo medio'), ('ALTO', 'Alto riesgo')], max_length=5)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('RESUELTO_LOCAL', 'Resuelto en el mismo nivel'), ('EN_COLA_INTERCONSULTA', 'En cola de interconsulta')], default='REGISTRADO', max_length=25)),
                ('fecha_resolucion', models.DateTimeField(blank=True, help_text='Fecha del cierre del caso, en cualquiera de los dos caminos.', null=True)),
                ('notas_clinicas', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='interconsulta.establecimientosalud')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='interconsulta.paciente')),
            ],
            options={
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('MEDICO_GENERAL', 'Médico general'), ('SERUMISTA', 'Serumista'), ('ESPECIALISTA', 'Especialista')], max_length=20)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesionales', to='interconsulta.establecimientosalud')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='ColaInterconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('URGENTE', 'Urgente'), ('ALTA', 'Alta'), ('MEDIA', 'Media')], max_length=10)),
                ('estado', models.CharField(choices=[('EN_ESPERA', 'En espera'), ('EN_ATENCION', 'En atención'), ('RESUELTO', 'Resuelto'), ('CANCELADO', 'Cancelado')], default='EN_ESPERA', max_length=15)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_especialista', models.TextField(blank=True)),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cola_interconsulta', to='interconsulta.casotriaje')),
                ('especialista_asignado', models.ForeignKey(blank=True, limit_choices_to={'rol': 'ESPECIALISTA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_asignados', to='interconsulta.profesional')),
            ],
            options={
                'verbose_name_plural': 'Colas de interconsulta',
                'ordering': ['fecha_ingreso'],
            },
        ),
        migrations.AddField(
            model_name='casotriaje',
            name='profesional_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_creados', to='interconsulta.profesional'),
        ),
        migrations.AddField(
            model_name='casotriaje',
            name='profesional_resuelve',
            field=models.ForeignKey(blank=True, help_text='Profesional que cerró el caso, ya sea resolviéndolo en el mismo nivel (RESUELTO_LOCAL) o como especialista que atendió la interconsulta (EN_COLA_INTERCONSULTA -> resuelta). No se restringe por rol porque aplica a ambos caminos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_resueltos', to='interconsulta.profesional'),
        ),
    ]
