# Generated by Django 6.1.1 on 2026-09-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interconsulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casotriaje',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, help_text='Fecha del cierre del caso.', null=True),
        ),
        migrations.AlterField(
            model_name='casotriaje',
            name='profesional_resuelve',
            field=models.ForeignKey(blank=True, help_text='Profesional que cerró el caso', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_resueltos', to='interconsulta.profesional'),
        ),
    ]
