# Generated by Django 6.1.1 on 2026-09-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interconsulta', '0002_alter_casotriaje_fecha_resolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casotriaje',
            name='estado',
            field=models.CharField(choices=[('REGISTRADO', 'Registrado'), ('RESUELTO_LOCAL', 'Resuelto en el mismo nivel'), ('EN_COLA_INTERCONSULTA', 'En cola de interconsulta'), ('RESUELTO_INTERCONSULTA', 'Resuelto por interconsulta')], default='REGISTRADO', max_length=25),
        ),
    ]
