# Generated by Django 6.1.1 on 2026-09-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interconsulta', '0003_alter_casotriaje_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='casotriaje',
            name='imagen',
            field=models.ImageField(default='', upload_to='casos/%Y/%m/'),
            preserve_default=False,
        ),
    ]
